"""Tests for operational carbon per token (`plan --grid-region` / `--carbon-intensity`).

Emissions per token are the energy the planner already models times the carbon
intensity of the grid. Intensity is a property of the region, so it comes from a
pinned, date-stamped snapshot of Our World in Data's `carbon_intensity_elec`
(Ember lifecycle gCO2e/kWh), regenerated by scripts/build_carbon_data.py.

The honesty constraints under test:
- This is the SCI v1.1 operational term only, O = E x I. Embodied emissions (M) are
  not modelled, so it is never presented as a full SCI score.
- E is board power (TDP x POWER_UTILISATION) with no host or datacenter PUE, so it
  is a lower bound, and the output says so.
- A stale region year warns; an unknown TDP gives unknown carbon, never zero.
- A source value that cannot be the stated quantity (0 lifecycle) is excluded
  with its reason, not shipped.
"""

from __future__ import annotations

import datetime as dt
import importlib.util
import json
import pathlib
from dataclasses import asdict

import pytest
from typer.testing import CliRunner

from chimeraforge.cli import app
from chimeraforge.planner.carbon import grid_intensity, load_carbon
from chimeraforge.planner.constants import HOURS_PER_MONTH, POWER_UTILISATION
from chimeraforge.planner.service import run_plan

ROOT = pathlib.Path(__file__).resolve().parents[1]


def _builder():
    spec = importlib.util.spec_from_file_location(
        "build_carbon_data", ROOT / "scripts" / "build_carbon_data.py"
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


BASE = dict(model_size="8b", hardware="H100 80GB", request_rate=2.0, budget=1e9, quality_target=0.0)


def _plan(**over):
    kw = dict(BASE)
    kw.update(over)
    return run_plan(**kw)


class TestSnapshot:
    def test_bundled_file_validates(self):
        data = load_carbon()
        _builder().validate(data, dt.date.fromisoformat(data["captured_at"]))

    def test_provenance_travels_with_the_data(self):
        src = load_carbon()["source"]
        assert len(src["commit"]) == 40 and src["commit"] in src["url"]
        assert "CC BY 4.0" in src["license"] and "Ember" in src["attribution"]
        assert "Lifecycle" in src["title"]

    def test_values_match_the_pinned_source(self):
        # Read from owid-energy-data.csv at the pinned commit (7e387a1).
        r = load_carbon()["regions"]
        assert r["USA"] == {"name": "United States", "year": 2025, "gco2e_per_kwh": 384.4}
        assert r["FRA"]["gco2e_per_kwh"] == 41.44
        assert r["IND"]["gco2e_per_kwh"] == 670.13

    def test_physically_ordered(self):
        # Nuclear/hydro grids below mixed grids below coal-heavy ones.
        r = {k: v["gco2e_per_kwh"] for k, v in load_carbon()["regions"].items()}
        assert max(r["NOR"], r["FRA"]) < r["DEU"] < min(r["POL"], r["IND"])

    def test_zero_lifecycle_value_is_excluded_with_reason(self):
        data = load_carbon()
        assert "CAF" not in data["regions"]
        assert "never zero" in data["excluded"]["CAF"]


class TestBuilderParsing:
    CSV = (
        "country,year,iso_code,carbon_intensity_elec\n"
        "Testland,2023,TST,500.0\n"
        "Testland,2024,TST,450.0\n"
        "Testland,2025,TST,\n"
        "World,2025,OWID_WRL,480.0\n"
        "Europe,2025,,300.0\n"
        "Hydroland,2024,HYD,0.0\n"
    )

    def test_latest_year_with_a_value_per_country(self):
        regions = _builder().parse_regions(self.CSV)
        assert regions["TST"] == {"name": "Testland", "year": 2024, "gco2e_per_kwh": 450.0}

    def test_aggregates_excluded(self):
        regions = _builder().parse_regions(self.CSV)
        assert set(regions) == {"TST", "HYD"}

    def test_zero_split_out(self):
        b = _builder()
        kept, excluded = b.split_excluded(b.parse_regions(self.CSV))
        assert "HYD" not in kept and "HYD" in excluded

    def test_validation_fails_loudly(self):
        b = _builder()
        data = load_carbon()
        broken = json.loads(json.dumps(data))
        broken["regions"]["USA"]["gco2e_per_kwh"] = 9000.0
        with pytest.raises(b.BuildError):
            b.validate(broken, dt.date(2026, 9, 26))
        broken = json.loads(json.dumps(data))
        del broken["source"]["license"]
        with pytest.raises(b.BuildError):
            b.validate(broken, dt.date(2026, 9, 26))


class TestGridIntensity:
    def test_iso_and_name_lookup(self):
        assert grid_intensity("usa").gco2e_per_kwh == 384.4
        g = grid_intensity("Germany")
        assert g.region == "DEU" and g.year == 2025

    def test_unknown_region(self):
        with pytest.raises(ValueError, match="unknown grid region"):
            grid_intensity("XXX")

    def test_excluded_region_says_why(self):
        with pytest.raises(ValueError, match="never zero"):
            grid_intensity("CAF")

    def test_custom_figure(self):
        g = grid_intensity(None, 120.0)
        assert g.gco2e_per_kwh == 120.0 and "your figure" in g.basis

    @pytest.mark.parametrize("bad", [0.0, -5.0, 5000.0])
    def test_custom_out_of_range(self, bad):
        with pytest.raises(ValueError, match="carbon_intensity"):
            grid_intensity(None, bad)

    def test_both_is_an_error(self):
        with pytest.raises(ValueError, match="not both"):
            grid_intensity("USA", 100.0)

    def test_neither_is_off(self):
        assert grid_intensity(None, None) is None

    def test_staleness_expires_loudly(self):
        assert not grid_intensity("USA", today=dt.date(2026, 9, 26)).stale
        assert grid_intensity("USA", today=dt.date(2030, 1, 1)).stale
        assert grid_intensity("ESH", today=dt.date(2026, 9, 26)).stale


class TestPlan:
    def test_off_by_default(self):
        a, b = _plan().candidates, _plan(grid_region=None, carbon_intensity=None).candidates
        assert [asdict(c) for c in a] == [asdict(c) for c in b]
        c = a[0]
        assert c.co2e_g_per_1m_tok is None and c.co2e_kg_month is None
        assert not any("carbon" in w.lower() for w in c.warnings)

    def test_hand_checked_arithmetic(self):
        for c in _plan(grid_region="USA").candidates[:5]:
            kw = c.tdp_watts * POWER_UTILISATION / 1000.0 * c.gpus_total
            kwh_per_1m = kw * 1e6 / (c.total_throughput_tps * 3600.0)
            assert c.co2e_g_per_1m_tok == pytest.approx(kwh_per_1m * 384.4, rel=2e-3)
            kg_month = kw * HOURS_PER_MONTH * 384.4 / 1000.0
            assert c.co2e_kg_month == pytest.approx(kg_month, rel=2e-3)

    def test_linear_in_intensity(self):
        us = _plan(grid_region="USA").candidates[0]
        fr = _plan(grid_region="FRA").candidates[0]
        assert fr.co2e_g_per_1m_tok / us.co2e_g_per_1m_tok == pytest.approx(41.44 / 384.4, rel=2e-3)

    def test_per_token_invariant_in_replicas(self):
        lo = _plan(grid_region="USA", request_rate=1.0, model_size="1b").candidates
        hi = _plan(grid_region="USA", request_rate=40.0, model_size="1b").candidates
        key = lambda c: (c.model, c.quant, c.backend, c.effective_batch)  # noqa: E731
        lo_by = {key(c): c for c in lo}
        shared = [c for c in hi if key(c) in lo_by and c.n_agents != lo_by[key(c)].n_agents]
        assert shared, "expected a cell sized to different replica counts"
        for c in shared:
            assert c.co2e_g_per_1m_tok == pytest.approx(lo_by[key(c)].co2e_g_per_1m_tok, rel=2e-3)

    def test_labeled_as_operational_only(self):
        c = _plan(grid_region="USA").candidates[0]
        assert "Ember" in c.carbon_basis and "2025" in c.carbon_basis
        text = " ".join(c.warnings)
        assert "SCI" in text and "embodied" in text and "not a full SCI" in text
        assert "lower bound" in text

    def test_unknown_tdp_is_unknown_not_zero(self):
        c = run_plan(
            hardware="RTX 6090 48GB",
            gpu_overrides={"vram_gb": 48, "bandwidth_gbps": 1500, "cost_per_hour": 0.05},
            grid_region="USA",
            **{k: v for k, v in BASE.items() if k != "hardware"},
        ).candidates[0]
        assert c.co2e_g_per_1m_tok is None and c.co2e_kg_month is None
        assert any("carbon unknown" in w for w in c.warnings)

    def test_stale_region_warns(self):
        c = _plan(grid_region="ESH").candidates[0]
        assert any("stale" in w and "2009" in w for w in c.warnings)


runner = CliRunner()
CLI = ["plan", "--model-size", "8b", "--hardware", "H100 80GB", "--budget", "1000000"]


class TestCli:
    def test_json_carries_carbon(self):
        r = runner.invoke(app, [*CLI, "--grid-region", "USA", "--json"])
        assert r.exit_code == 0, r.output
        row = json.loads(r.output)[0]
        assert row["co2e_g_per_1m_tok"] > 0 and "Ember" in row["carbon_basis"]

    def test_human_output_attributes_the_source(self):
        r = runner.invoke(app, [*CLI, "--grid-region", "FRA"], terminal_width=160)
        assert r.exit_code == 0, r.output
        assert "gCO2e" in r.output and "Ember" in r.output

    @pytest.mark.parametrize(
        "extra",
        [
            ["--grid-region", "XXX"],
            ["--grid-region", "USA", "--carbon-intensity", "100"],
            ["--carbon-intensity", "0"],
        ],
    )
    def test_bad_input_fails_clean(self, extra):
        r = runner.invoke(app, [*CLI, *extra])
        assert r.exit_code == 1
        assert "Traceback" not in r.output

    def test_report_carries_carbon_and_reproduces(self, tmp_path):
        out = tmp_path / "brief.md"
        r = runner.invoke(app, [*CLI, "--grid-region", "USA", "--report", str(out)])
        assert r.exit_code == 0, r.output
        text = out.read_text(encoding="utf-8")
        assert "gCO2e" in text and "--grid-region USA" in text


class TestMcp:
    def test_mcp_grid_region(self):
        from chimeraforge.mcp_server import plan_deployment

        out = plan_deployment(model_size="8b", hardware="H100 80GB", grid_region="FRA")
        assert out["ok"], out
        assert out["recommended"]["co2e_g_per_1m_tok"] > 0

    def test_mcp_bad_region(self):
        from chimeraforge.mcp_server import plan_deployment

        out = plan_deployment(model_size="8b", hardware="H100 80GB", grid_region="XXX")
        assert not out["ok"] and "unknown grid region" in out["error"]
