"""Regenerate and validate the bundled GPU specification dataset.

P8.6. `hardware.py` was a hand-typed dict of 22 `GPUSpec` literals with a prose
comment block for provenance -- no `captured_at`, no per-field source, no
regeneration path, and `$/hr` described in its own comment as "approximate". That
is the project's own house rule ("Regenerable, not hand-typed... A dataset
without a `captured_at` and a source is not shippable") unmet in the one dataset
that drives every throughput number, since decode is modelled as bandwidth-bound.

This mirrors `build_cost_data.py`: the values and their sources live here, the
bundled JSON is generated, and validation is strict and always runs.

Usage
-----
    python scripts/build_hardware_data.py --check    # validate the bundled file
    python scripts/build_hardware_data.py --write    # regenerate it

Two things this deliberately does NOT do.

It does not scrape. `techpowerup.com/gpu-specs/` returns HTTP 403 to automated
fetch, and vendor spec pages are JavaScript-rendered marketing pages whose layout
changes without notice. So the source URL is recorded per field and the value is
updated by a human reading that page, with `captured_at` bumped -- the point is
that every number traces to a page someone read on a known date, not that a
scrape always succeeds.

It does not invent a figure to fill a gap. Consumer memory bandwidth and dense
tensor TFLOPS are frequently absent from vendor pages. A field with no vendor
source is `null`, and a `null` field disables the prediction that depends on it
rather than defaulting -- unknown bandwidth means throughput is `unknown`, not
roofline-with-a-guess.

**Every value below is the value `hardware.py` already carried.** This item is a
migration plus a provenance record; a spec change would be a separate, arguable
thing, and mixing the two would hide it.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATASET = ROOT / "src" / "chimeraforge" / "planner" / "data" / "hardware.json"


def _load_constants():
    """constants.py by file path, NOT through the package: importing
    chimeraforge.planner loads hardware.json, so a schema change could never be
    regenerated by the script that regenerates it. constants.py imports nothing."""
    import importlib.util

    path = ROOT / "src" / "chimeraforge" / "planner" / "constants.py"
    spec = importlib.util.spec_from_file_location("_chimeraforge_constants", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


AMORTISATION_HOURS = _load_constants().AMORTISATION_HOURS

SCHEMA_VERSION = 1

# How a `$/hr` figure was arrived at. The old field mixed two incompatible
# quantities under one name -- its own comment said datacenter values are
# "approximate on-demand cloud rates" and consumer values are "amortised card
# cost" -- and the field drives the budget gate, $/1M-tok, and the
# self-host-vs-API break-even, so the basis has to travel with it.
#
# The datacenter values also do not match the basis they claimed: H100 at
# $2.50/hr and B200 at $5.50/hr track GPU *marketplace* rates, roughly 4-5x
# below hyperscaler on-demand. They are relabelled to what they are rather than
# being changed, because changing them is a pricing decision and this is a
# migration.
BASIS_MARKETPLACE = "marketplace"
BASIS_HYPERSCALER = "hyperscaler-on-demand"
BASIS_AMORTISED = "amortised-purchase"
PRICE_BASES = {BASIS_MARKETPLACE, BASIS_HYPERSCALER, BASIS_AMORTISED}

# How a TFLOPS figure was derived, per the rule `hardware.py`'s comment block
# states. `dense` is a datasheet row. `halved-with-sparsity` is a datasheet that
# publishes only a sparse figure, divided by two -- defensible, but not a
# datasheet row, and NOT universally safe: AMD prints both columns for some parts
# and no sparsity figure at all for others, so halving an unlabeled headline
# would understate a dense number by 2x. `derived-2x-fp32` is the consumer rule.
TFLOPS_DENSE = "dense"
TFLOPS_HALVED = "halved-with-sparsity"
TFLOPS_2X_FP32 = "derived-2x-fp32"
TFLOPS_FP32_ACCUM = "fp32-accumulate-dense"
# The two reasons `fp16_tflops` is null. `unlabeled-by-vendor`: the vendor prints
# a figure without saying whether it is dense or with-sparsity, so neither using
# nor halving it is a reading of the datasheet. `not-published`: no FP16 matrix
# figure at all. Either way the value stays null and TTFT is only a floor.
TFLOPS_UNLABELED = "unlabeled-by-vendor"
TFLOPS_UNPUBLISHED = "not-published"
TFLOPS_NULL_BASES = {TFLOPS_UNLABELED, TFLOPS_UNPUBLISHED}
TFLOPS_BASES = {TFLOPS_DENSE, TFLOPS_HALVED, TFLOPS_2X_FP32, TFLOPS_FP32_ACCUM} | TFLOPS_NULL_BASES

NVIDIA_GEFORCE = "https://www.nvidia.com/en-us/geforce/graphics-cards/"
NVIDIA_LAPTOPS = "https://www.nvidia.com/en-us/geforce/laptops/compare/"
NVIDIA_DC = "https://www.nvidia.com/en-us/data-center/"
AMD_MI300X = "https://www.amd.com/en/products/accelerators/instinct/mi300/mi300x.html"

# name, vram_gb, bandwidth, $/hr, price_basis, fp16_tflops, tflops_basis, tdp,
# interconnect, fp8, source_url, captured_at
#
# `captured_at` is the date the figure was last read from `source_url`. The
# reference card's specs were re-read on 2026-08-22 when 0.30.4 corrected them
# (see hardware.py's comment block); the rest carry the date this dataset was
# first assembled from the values that comment block documents.
_ASSEMBLED = "2026-09-05"
_REFERENCE_READ = "2026-08-22"

GPUS: list[dict] = [
    # -- Consumer, NVIDIA Ada (PCIe 4.0 = 64 GB/s) --------------------------
    dict(
        name="RTX 4060 8GB",
        vram_gb=8.0,
        bandwidth_gbps=272.0,
        cost_per_hour=0.020,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=30.2,
        tflops_basis=TFLOPS_2X_FP32,
        tdp_watts=115.0,
        interconnect_gbps=64.0,
        fp8_supported=True,
        source_url=NVIDIA_GEFORCE,
        captured_at=_ASSEMBLED,
    ),
    dict(
        name="RTX 4060 Ti 8GB",
        vram_gb=8.0,
        bandwidth_gbps=288.0,
        cost_per_hour=0.025,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=44.1,
        tflops_basis=TFLOPS_2X_FP32,
        tdp_watts=160.0,
        interconnect_gbps=64.0,
        fp8_supported=True,
        source_url=NVIDIA_GEFORCE,
        captured_at=_ASSEMBLED,
    ),
    dict(
        name="RTX 4060 Ti 16GB",
        vram_gb=16.0,
        bandwidth_gbps=288.0,
        cost_per_hour=0.030,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=44.1,
        tflops_basis=TFLOPS_2X_FP32,
        tdp_watts=165.0,
        interconnect_gbps=64.0,
        fp8_supported=True,
        source_url=NVIDIA_GEFORCE,
        captured_at=_ASSEMBLED,
    ),
    dict(
        name="RTX 4070 12GB",
        vram_gb=12.0,
        bandwidth_gbps=504.0,
        cost_per_hour=0.030,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=58.4,
        tflops_basis=TFLOPS_2X_FP32,
        tdp_watts=200.0,
        interconnect_gbps=64.0,
        fp8_supported=True,
        source_url=NVIDIA_GEFORCE,
        captured_at=_ASSEMBLED,
    ),
    dict(
        name="RTX 4070 Ti 12GB",
        vram_gb=12.0,
        bandwidth_gbps=504.0,
        cost_per_hour=0.035,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=80.2,
        tflops_basis=TFLOPS_2X_FP32,
        tdp_watts=285.0,
        interconnect_gbps=64.0,
        fp8_supported=True,
        source_url=NVIDIA_GEFORCE,
        captured_at=_ASSEMBLED,
    ),
    # The reference rig: an RTX 4080 LAPTOP part, 12 GB GDDR6 on a 192-bit bus at
    # a 60-150 W TGP. Its bandwidth is the denominator of every cross-GPU
    # extrapolation and of MBU_DEFAULT, so it is the one entry whose figures were
    # re-read from the vendor page rather than inherited.
    dict(
        name="RTX 4080 12GB",
        vram_gb=12.0,
        bandwidth_gbps=432.0,
        cost_per_hour=0.035,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=67.7,
        tflops_basis=TFLOPS_2X_FP32,
        tdp_watts=150.0,
        interconnect_gbps=64.0,
        fp8_supported=True,
        source_url=NVIDIA_LAPTOPS,
        captured_at=_REFERENCE_READ,
    ),
    dict(
        name="RTX 4080 16GB",
        vram_gb=16.0,
        bandwidth_gbps=717.0,
        cost_per_hour=0.045,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=97.5,
        tflops_basis=TFLOPS_2X_FP32,
        tdp_watts=320.0,
        interconnect_gbps=64.0,
        fp8_supported=True,
        source_url=NVIDIA_GEFORCE,
        captured_at=_ASSEMBLED,
    ),
    dict(
        name="RTX 4090 24GB",
        vram_gb=24.0,
        bandwidth_gbps=1008.0,
        cost_per_hour=0.060,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=165.2,
        tflops_basis=TFLOPS_2X_FP32,
        tdp_watts=450.0,
        interconnect_gbps=64.0,
        fp8_supported=True,
        source_url=NVIDIA_GEFORCE,
        captured_at=_ASSEMBLED,
    ),
    # -- Consumer, NVIDIA Blackwell (GDDR7, PCIe 5.0 = 128 GB/s) ------------
    dict(
        name="RTX 5070 12GB",
        vram_gb=12.0,
        bandwidth_gbps=672.0,
        cost_per_hour=0.030,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=61.7,
        tflops_basis=TFLOPS_2X_FP32,
        tdp_watts=250.0,
        interconnect_gbps=128.0,
        fp8_supported=True,
        source_url=NVIDIA_GEFORCE,
        captured_at=_ASSEMBLED,
    ),
    dict(
        name="RTX 5070 Ti 16GB",
        vram_gb=16.0,
        bandwidth_gbps=896.0,
        cost_per_hour=0.038,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=87.9,
        tflops_basis=TFLOPS_2X_FP32,
        tdp_watts=300.0,
        interconnect_gbps=128.0,
        fp8_supported=True,
        source_url=NVIDIA_GEFORCE,
        captured_at=_ASSEMBLED,
    ),
    dict(
        name="RTX 5080 16GB",
        vram_gb=16.0,
        bandwidth_gbps=960.0,
        cost_per_hour=0.045,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=112.6,
        tflops_basis=TFLOPS_2X_FP32,
        tdp_watts=360.0,
        interconnect_gbps=128.0,
        fp8_supported=True,
        source_url=NVIDIA_GEFORCE,
        captured_at=_ASSEMBLED,
    ),
    dict(
        name="RTX 5090 32GB",
        vram_gb=32.0,
        bandwidth_gbps=1792.0,
        cost_per_hour=0.075,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=209.5,
        tflops_basis=TFLOPS_2X_FP32,
        tdp_watts=575.0,
        interconnect_gbps=128.0,
        fp8_supported=True,
        source_url=NVIDIA_GEFORCE,
        captured_at=_ASSEMBLED,
    ),
    # -- Consumer, NVIDIA Ampere (no FP8 tensor cores) ---------------------
    dict(
        name="RTX 3090 24GB",
        vram_gb=24.0,
        bandwidth_gbps=936.0,
        cost_per_hour=0.040,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=71.0,
        tflops_basis=TFLOPS_FP32_ACCUM,
        tdp_watts=350.0,
        interconnect_gbps=64.0,
        fp8_supported=False,
        source_url=NVIDIA_GEFORCE,
        captured_at=_ASSEMBLED,
    ),
    dict(
        name="RTX 3080 10GB",
        vram_gb=10.0,
        bandwidth_gbps=760.0,
        cost_per_hour=0.025,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=59.5,
        tflops_basis=TFLOPS_FP32_ACCUM,
        tdp_watts=320.0,
        interconnect_gbps=64.0,
        fp8_supported=False,
        source_url=NVIDIA_GEFORCE,
        captured_at=_ASSEMBLED,
    ),
    # -- Data-center, NVIDIA (NVLink) --------------------------------------
    dict(
        name="A100 40GB",
        vram_gb=40.0,
        bandwidth_gbps=1555.0,
        cost_per_hour=1.10,
        price_basis=BASIS_MARKETPLACE,
        fp16_tflops=312.0,
        tflops_basis=TFLOPS_DENSE,
        tdp_watts=400.0,
        interconnect_gbps=600.0,
        fp8_supported=False,
        source_url=NVIDIA_DC + "a100/",
        captured_at=_ASSEMBLED,
    ),
    dict(
        name="A100 80GB",
        vram_gb=80.0,
        bandwidth_gbps=2039.0,
        cost_per_hour=1.60,
        price_basis=BASIS_MARKETPLACE,
        fp16_tflops=312.0,
        tflops_basis=TFLOPS_DENSE,
        tdp_watts=400.0,
        interconnect_gbps=600.0,
        fp8_supported=False,
        source_url=NVIDIA_DC + "a100/",
        captured_at=_ASSEMBLED,
    ),
    dict(
        name="H100 80GB",
        vram_gb=80.0,
        bandwidth_gbps=3352.0,
        cost_per_hour=2.50,
        price_basis=BASIS_MARKETPLACE,
        fp16_tflops=989.0,
        tflops_basis=TFLOPS_DENSE,
        tdp_watts=700.0,
        interconnect_gbps=900.0,
        fp8_supported=True,
        source_url=NVIDIA_DC + "h100/",
        captured_at=_ASSEMBLED,
    ),
    # H200 shares H100's GH100 compute die; only its memory differs.
    dict(
        name="H200 141GB",
        vram_gb=141.0,
        bandwidth_gbps=4800.0,
        cost_per_hour=3.50,
        price_basis=BASIS_MARKETPLACE,
        fp16_tflops=989.0,
        tflops_basis=TFLOPS_DENSE,
        tdp_watts=700.0,
        interconnect_gbps=900.0,
        fp8_supported=True,
        source_url=NVIDIA_DC + "h200/",
        captured_at=_ASSEMBLED,
    ),
    # HGX B200 per-GPU datasheet figures (180 GB / 7.7 TB/s), not the 192 GB
    # raw-stack number. The datasheet prints only a with-sparsity FP16 figure
    # (4500), so the dense value is that halved -- recorded as such.
    dict(
        name="B200 180GB",
        vram_gb=180.0,
        bandwidth_gbps=7700.0,
        cost_per_hour=5.50,
        price_basis=BASIS_MARKETPLACE,
        fp16_tflops=2250.0,
        tflops_basis=TFLOPS_HALVED,
        tdp_watts=1000.0,
        interconnect_gbps=1800.0,
        fp8_supported=True,
        source_url=NVIDIA_DC + "dgx-b200/",
        captured_at=_ASSEMBLED,
    ),
    dict(
        name="L4 24GB",
        vram_gb=24.0,
        bandwidth_gbps=300.0,
        cost_per_hour=0.50,
        price_basis=BASIS_MARKETPLACE,
        fp16_tflops=121.0,
        tflops_basis=TFLOPS_DENSE,
        tdp_watts=72.0,
        interconnect_gbps=64.0,
        fp8_supported=True,
        source_url=NVIDIA_DC + "l4/",
        captured_at=_ASSEMBLED,
    ),
    dict(
        name="T4 16GB",
        vram_gb=16.0,
        bandwidth_gbps=320.0,
        cost_per_hour=0.35,
        price_basis=BASIS_MARKETPLACE,
        fp16_tflops=65.0,
        tflops_basis=TFLOPS_DENSE,
        tdp_watts=70.0,
        interconnect_gbps=64.0,
        fp8_supported=False,
        source_url=NVIDIA_DC + "tesla-t4/",
        captured_at=_ASSEMBLED,
    ),
    # -- Data-center, AMD (Infinity Fabric) --------------------------------
    # MI300X's sheet prints the dense 1307 directly, so it is a datasheet row
    # rather than a halved sparse one.
    dict(
        name="MI300X 192GB",
        vram_gb=192.0,
        bandwidth_gbps=5300.0,
        cost_per_hour=2.00,
        price_basis=BASIS_MARKETPLACE,
        fp16_tflops=1307.0,
        tflops_basis=TFLOPS_DENSE,
        tdp_watts=750.0,
        interconnect_gbps=896.0,
        fp8_supported=True,
        source_url=AMD_MI300X,
        captured_at=_ASSEMBLED,
    ),
]

# -- 2026 parts (P8.6 item 6) ------------------------------------------------
# Every figure read from the vendor page, datasheet or press release in its
# `field_sources` entry on 2026-09-25; RX 9070 XT, MI355X, RTX PRO 6000 Max-Q
# and Arc Pro B65 were re-read independently against the live source. Units
# the vendor prints in TB/s or PFLOPs are converted x1000, nothing else.
#
# Conventions carried from the entries above: interconnect is the per-GPU
# bidirectional aggregate (PCIe 5.0 x16 = 128, x8 = 64; Infinity Fabric = links x
# per-link rate as the datasheet states it). A field the vendor does not
# publish is null. Excluded on purpose: MI430X, which AMD says is "expected to be
# available in 2027" -- not a 2026 planning part.
_2026 = "2026-09-25"
NV_RTXPRO_WP = (
    "https://www.nvidia.com/content/dam/en-zz/Solutions/design-visualization/"
    "quadro-product-literature/NVIDIA-RTX-Blackwell-PRO-GPU-Architecture-v1.0.pdf"
)
NV_RTXPRO_WS = (
    "https://www.nvidia.com/content/dam/en-zz/Solutions/data-center/"
    "rtx-pro-6000-blackwell-workstation-edition/"
    "workstation-blackwell-rtx-pro-6000-workstation-edition-nvidia-us-3519208-web.pdf"
)
NV_RTXPRO_MAXQ = (
    "https://www.nvidia.com/content/dam/en-zz/Solutions/products/workstations/"
    "professional-desktop-gpus/rtx-pro-6000-max-q/"
    "workstation-datasheet-blackwell-rtx-pro-6000-max-q-nvidia-us-5349650-web.pdf"
)
NV_RTXPRO_SERVER = "https://www.nvidia.com/en-us/data-center/rtx-pro-6000-blackwell-server-edition/"
AMD_DOCS = "https://www.amd.com/content/dam/amd/en/documents/"
AMD_MI325X = AMD_DOCS + "instinct-tech-docs/product-briefs/instinct-mi325x-datasheet.pdf"
AMD_MI350X = AMD_DOCS + "instinct-tech-docs/product-briefs/amd-instinct-mi350x-gpu-brochure.pdf"
AMD_MI355X = AMD_DOCS + "instinct-tech-docs/product-briefs/amd-instinct-mi355x-gpu-brochure.pdf"
AMD_MI455X = AMD_DOCS + "products/accelerators/instinct/amd-instinct-mi455x_brochure.pdf"
AMD_MI455X_PAGE = "https://www.amd.com/en/products/accelerators/instinct/mi400/mi455x.html"
INTEL_ARK = "https://www.intel.com/content/www/us/en/products/sku/"
INTEL_B60 = INTEL_ARK + "243916/intel-arc-pro-b60-graphics/specifications.html"
INTEL_B65 = INTEL_ARK + "245796/intel-arc-pro-b65-graphics/specifications.html"
AMD_RADEON = "https://www.amd.com/en/products/graphics/desktops/radeon/9000-series/"
AMD_RDNA4_PR = (
    "https://ir.amd.com/news-events/press-releases/detail/1238/"
    "amd-unveils-next-generation-amd-rdna-4-architecture-with-the-launch-of-amd-radeon-"
    "rx-9000-series-graphics-cards"
)
AMD_9060XT_PR = (
    "https://www.amd.com/en/newsroom/press-releases/"
    "2025-5-20-amd-introduces-new-radeon-graphics-cards-and-ryzen.html"
)
AMD_R9700 = (
    "https://www.amd.com/en/products/graphics/workstations/radeon-ai-pro/ai-9000-series/"
    "amd-radeon-ai-pro-r9700.html"
)

# AMD's published suggested e-tail prices (press releases above), USD.
SEP_USD = {"RX 9070 16GB": 549.0, "RX 9070 XT 16GB": 599.0, "RX 9060 XT 16GB": 349.0}


def _amortised(name: str) -> float:
    """Vendor SEP spread over AMORTISATION_HOURS, rounded to the stored precision."""
    return round(SEP_USD[name] / AMORTISATION_HOURS, 4)


GPUS += [
    # NVIDIA prints dense and with-sparsity as one "dense/sparse" pair; the first
    # figure is the dense one, FP16 tensor with FP32 accumulate.
    dict(
        name="RTX PRO 6000 Blackwell Workstation 96GB",
        vram_gb=96.0,
        bandwidth_gbps=1792.0,
        cost_per_hour=None,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=503.8,
        tflops_basis=TFLOPS_FP32_ACCUM,
        tdp_watts=600.0,
        interconnect_gbps=128.0,
        fp8_supported=True,
        source_url=NV_RTXPRO_WS,
        captured_at=_2026,
        field_sources={"fp16_tflops": NV_RTXPRO_WP, "fp8_supported": NV_RTXPRO_WP},
    ),
    dict(
        name="RTX PRO 6000 Blackwell Max-Q 96GB",
        vram_gb=96.0,
        bandwidth_gbps=1792.0,
        cost_per_hour=None,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=438.9,
        tflops_basis=TFLOPS_FP32_ACCUM,
        tdp_watts=300.0,
        interconnect_gbps=128.0,
        fp8_supported=True,
        source_url=NV_RTXPRO_MAXQ,
        captured_at=_2026,
        field_sources={"fp16_tflops": NV_RTXPRO_WP, "fp8_supported": NV_RTXPRO_WP},
    ),
    # The page prints "FP16 | BF16 Tensor Core 1 PFLOP" with no dense/sparse label,
    # the datasheet omits FP16 tensor entirely, and the architecture whitepaper
    # covers only the workstation cards. Neither using nor halving it is a reading.
    dict(
        name="RTX PRO 6000 Blackwell Server 96GB",
        vram_gb=96.0,
        bandwidth_gbps=1597.0,
        cost_per_hour=None,
        price_basis=BASIS_MARKETPLACE,
        fp16_tflops=None,
        tflops_basis=TFLOPS_UNLABELED,
        tdp_watts=600.0,
        interconnect_gbps=128.0,
        fp8_supported=True,
        source_url=NV_RTXPRO_SERVER,
        captured_at=_2026,
    ),
    # MI325X dense FP16 1307.4 matches MI300X's 1307.0: same CDNA3 compute, which
    # confirms the dense column was read.
    dict(
        name="MI325X 256GB",
        vram_gb=256.0,
        bandwidth_gbps=6000.0,
        cost_per_hour=None,
        price_basis=BASIS_MARKETPLACE,
        fp16_tflops=1307.4,
        tflops_basis=TFLOPS_DENSE,
        tdp_watts=1000.0,
        interconnect_gbps=7 * 128.0,
        fp8_supported=True,
        source_url=AMD_MI325X,
        captured_at=_2026,
    ),
    dict(
        name="MI350X 288GB",
        vram_gb=288.0,
        bandwidth_gbps=8000.0,
        cost_per_hour=None,
        price_basis=BASIS_MARKETPLACE,
        fp16_tflops=2309.6,
        tflops_basis=TFLOPS_DENSE,
        tdp_watts=1000.0,
        interconnect_gbps=round(7 * 153.6, 1),
        fp8_supported=True,
        source_url=AMD_MI350X,
        captured_at=_2026,
    ),
    dict(
        name="MI355X 288GB",
        vram_gb=288.0,
        bandwidth_gbps=8000.0,
        cost_per_hour=None,
        price_basis=BASIS_MARKETPLACE,
        fp16_tflops=2516.6,
        tflops_basis=TFLOPS_DENSE,
        tdp_watts=1400.0,
        interconnect_gbps=round(7 * 153.6, 1),
        fp8_supported=True,
        source_url=AMD_MI355X,
        captured_at=_2026,
    ),
    # AMD publishes no board power and no PCIe spec for MI455X. Its interconnect
    # is the UALoE scale-up figure, stated by AMD as bidirectional.
    dict(
        name="MI455X 432GB",
        vram_gb=432.0,
        bandwidth_gbps=23300.0,
        cost_per_hour=None,
        price_basis=BASIS_MARKETPLACE,
        fp16_tflops=5033.0,
        tflops_basis=TFLOPS_DENSE,
        tdp_watts=None,
        interconnect_gbps=3600.0,
        fp8_supported=True,
        source_url=AMD_MI455X,
        captured_at=_2026,
        field_sources={"interconnect_gbps": AMD_MI455X_PAGE},
    ),
    # Intel publishes FP32 (12.28 TFLOPS) and INT8 TOPS, but no FP16 matrix or
    # FP8 figure. FP8 is therefore refused rather than assumed.
    dict(
        name="Arc Pro B60 24GB",
        vram_gb=24.0,
        bandwidth_gbps=456.0,
        cost_per_hour=None,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=None,
        tflops_basis=TFLOPS_UNPUBLISHED,
        tdp_watts=200.0,
        interconnect_gbps=64.0,
        fp8_supported=False,
        source_url=INTEL_B60,
        captured_at=_2026,
    ),
    dict(
        name="Arc Pro B65 32GB",
        vram_gb=32.0,
        bandwidth_gbps=608.0,
        cost_per_hour=None,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=None,
        tflops_basis=TFLOPS_UNPUBLISHED,
        tdp_watts=200.0,
        interconnect_gbps=128.0,
        fp8_supported=False,
        source_url=INTEL_B65,
        captured_at=_2026,
    ),
    # RDNA4: AMD prints a dense and a with-structured-sparsity row; the dense row
    # is used. Board power is AMD's "Typical Board Power (Desktop)".
    dict(
        name="RX 9070 16GB",
        vram_gb=16.0,
        bandwidth_gbps=640.0,
        cost_per_hour=_amortised("RX 9070 16GB"),
        price_basis=BASIS_AMORTISED,
        fp16_tflops=145.0,
        tflops_basis=TFLOPS_DENSE,
        tdp_watts=220.0,
        interconnect_gbps=128.0,
        fp8_supported=True,
        source_url=AMD_RADEON + "amd-radeon-rx-9070.html",
        captured_at=_2026,
        field_sources={"cost_per_hour": AMD_RDNA4_PR},
    ),
    dict(
        name="RX 9070 XT 16GB",
        vram_gb=16.0,
        bandwidth_gbps=640.0,
        cost_per_hour=_amortised("RX 9070 XT 16GB"),
        price_basis=BASIS_AMORTISED,
        fp16_tflops=195.0,
        tflops_basis=TFLOPS_DENSE,
        tdp_watts=304.0,
        interconnect_gbps=128.0,
        fp8_supported=True,
        source_url=AMD_RADEON + "amd-radeon-rx-9070xt.html",
        captured_at=_2026,
        field_sources={"cost_per_hour": AMD_RDNA4_PR},
    ),
    dict(
        name="RX 9060 XT 16GB",
        vram_gb=16.0,
        bandwidth_gbps=320.0,
        cost_per_hour=_amortised("RX 9060 XT 16GB"),
        price_basis=BASIS_AMORTISED,
        fp16_tflops=103.0,
        tflops_basis=TFLOPS_DENSE,
        tdp_watts=160.0,
        interconnect_gbps=128.0,
        fp8_supported=True,
        source_url=AMD_RADEON + "amd-radeon-rx-9060xt.html",
        captured_at=_2026,
        field_sources={"cost_per_hour": AMD_9060XT_PR, "fp8_supported": AMD_9060XT_PR},
    ),
    # AMD's standalone price for the R9700 appears only in press coverage, not on
    # an AMD page, so it stays null.
    dict(
        name="Radeon AI PRO R9700 32GB",
        vram_gb=32.0,
        bandwidth_gbps=640.0,
        cost_per_hour=None,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=191.0,
        tflops_basis=TFLOPS_DENSE,
        tdp_watts=300.0,
        interconnect_gbps=128.0,
        fp8_supported=True,
        source_url=AMD_R9700,
        captured_at=_2026,
    ),
]

# -- Unified-memory devices (P8.6 item 4) --------------------------------------
# CPU and GPU share one pool, so `vram_gb` is the LARGEST configuration sold and
# `memory_options_gb` lists every configuration; a plan uses the share the user
# states (--unified-memory-fraction), and --hardware auto uses the detected size.
# Read 2026-09-26 from Apple's current Mac spec pages / newsroom (the M4 iMac and
# the A18 Pro MacBook Neo are still sold), AMD's Ryzen AI Halo pages and NVIDIA's
# DGX Spark docs; M5 Max and M5 Ultra bandwidth and AMD's FP16 line re-read
# against the live pages. Deliberately null, per the dataset's rules:
#   - Apple publishes no GPU TFLOPS, and no chip power (only whole-system figures).
#   - AMD's "60 FP16 TFLOPS" is unlabeled dense/sparse, so it is not used.
#   - NVIDIA publishes only "1 PFLOP FP4" with sparsity for DGX Spark, no FP16.
#   - Prices: Apple sells configured Macs, not chips, so a chip price would be one
#     configuration's; the DGX Spark price is not on an NVIDIA page.
#   - M5 Ultra 512 GB is announced but not orderable ("coming late October").
#   - Interconnect: single devices; tensor parallelism across them is not modelled.
_UNI = "2026-09-26"
APPLE = "https://www.apple.com/"
AMD_HALO = (
    "https://www.amd.com/en/products/processors/desktops/ryzen/ryzen-ai-halo/"
    "ryzen-ai-max-plus-395.html"
)
NV_SPARK = "https://docs.nvidia.com/dgx/dgx-spark/hardware.html"


def _unified(
    name,
    memory,
    bandwidth,
    source,
    *,
    tdp=None,
    tflops_basis=TFLOPS_UNPUBLISHED,
    field_sources=None,
    **extra,
):
    return dict(
        name=name,
        vram_gb=float(max(memory)),
        memory_options_gb=[float(m) for m in memory],
        bandwidth_gbps=float(bandwidth),
        cost_per_hour=None,
        price_basis=BASIS_AMORTISED,
        fp16_tflops=None,
        tflops_basis=tflops_basis,
        tdp_watts=tdp,
        interconnect_gbps=None,
        fp8_supported=False,  # no vendor states FP8 matrix support for these
        source_url=source,
        captured_at=_UNI,
        **({"field_sources": field_sources} if field_sources else {}),
        **extra,
    )


GPUS += [
    _unified("Apple A18 Pro 5-core GPU 8GB", [8], 60, APPLE + "macbook-neo/specs/"),
    _unified("Apple M4 8-core GPU 24GB", [16, 24], 120, APPLE + "imac/specs/"),
    _unified("Apple M4 10-core GPU 32GB", [16, 24, 32], 120, APPLE + "imac/specs/"),
    _unified("Apple M5 8-core GPU 16GB", [16], 153, APPLE + "macbook-air/specs/"),
    _unified("Apple M5 10-core GPU 32GB", [16, 24, 32], 153, APPLE + "macbook-air/specs/"),
    # M6 bandwidth depends on the memory configuration, per the Mac mini specs.
    _unified("Apple M6 16GB", [16], 153, APPLE + "mac-mini/specs/"),
    _unified("Apple M6 32GB", [24, 32], 170, APPLE + "mac-mini/specs/"),
    _unified("Apple M5 Pro 16-core GPU 48GB", [24, 48], 307, APPLE + "macbook-pro/specs/"),
    _unified("Apple M5 Pro 20-core GPU 64GB", [24, 48, 64], 307, APPLE + "macbook-pro/specs/"),
    _unified("Apple M5 Max 32-core GPU 36GB", [36], 460, APPLE + "macbook-pro/specs/"),
    _unified("Apple M5 Max 40-core GPU 128GB", [48, 64, 128], 614, APPLE + "macbook-pro/specs/"),
    # "1.2TB/s memory bandwidth" for both Ultra variants (converted x1000).
    _unified("Apple M5 Ultra 64-core GPU 256GB", [96, 256], 1200, APPLE + "mac-studio/specs/"),
    _unified("Apple M5 Ultra 80-core GPU 256GB", [96, 256], 1200, APPLE + "mac-studio/specs/"),
    # 128 GB / 256 GB/s and "TDP 120W" are the Halo platform page's figures (the
    # chip's default TDP is 55 W, cTDP 45-120 W).
    _unified(
        "Ryzen AI Max+ 395 128GB",
        [128],
        256,
        AMD_HALO,
        tdp=120.0,
        tflops_basis=TFLOPS_UNLABELED,
    ),
    _unified("DGX Spark 128GB", [128], 273, NV_SPARK, tdp=140.0),
]

REQUIRED = (
    "name",
    "vram_gb",
    "bandwidth_gbps",
    "cost_per_hour",
    "price_basis",
    "fp16_tflops",
    "tflops_basis",
    "tdp_watts",
    "interconnect_gbps",
    "fp8_supported",
    "source_url",
    "captured_at",
    "vendor",
    "product_line",
    "unified_memory",
    "memory_options_gb",
)

# Vendor and product line, which the engine-support gate needs: SGLang and TGI
# document ROCm on Instinct only, TGI on Intel covers Data Center GPU Max only.
# Derived from the vendor's own product naming by one rule rather than typed per
# entry, and validated against a closed vocabulary.
PRODUCT_LINES = {
    "nvidia": {"geforce", "rtx-pro", "datacenter", "dgx-spark"},
    "amd": {"instinct", "radeon", "ryzen-ai-max"},
    "intel": {"arc-pro", "datacenter-max"},
    "apple": {"apple-silicon"},
}
# Product lines whose CPU and GPU share one memory pool.
UNIFIED_LINES = {"apple-silicon", "ryzen-ai-max", "dgx-spark"}


def vendor_line(name: str) -> tuple[str, str]:
    """(vendor, product_line) from a database name; raises on anything unknown."""
    if name.startswith("Apple "):
        return "apple", "apple-silicon"
    if name.startswith("Ryzen AI Max"):
        return "amd", "ryzen-ai-max"
    if name.startswith("DGX Spark"):
        return "nvidia", "dgx-spark"
    if name.startswith("RTX PRO "):
        return "nvidia", "rtx-pro"
    if name.startswith("RTX "):
        return "nvidia", "geforce"
    if name.split()[0] in {"A100", "H100", "H200", "B200", "L4", "T4"}:
        return "nvidia", "datacenter"
    if name.startswith("MI"):
        return "amd", "instinct"
    if name.startswith(("RX ", "Radeon ")):
        return "amd", "radeon"
    if name.startswith("Arc Pro "):
        return "intel", "arc-pro"
    raise ValidationError(f"{name}: no vendor/product-line rule matches this name")


# Sanity bounds. Anything outside these is far more likely to be a typo or a
# unit mix-up than a real part, so it fails the build rather than shipping.
BOUNDS = {
    "vram_gb": (1.0, 1024.0),
    "bandwidth_gbps": (10.0, 50000.0),
    "cost_per_hour": (0.001, 100.0),
    "fp16_tflops": (1.0, 100000.0),
    "tdp_watts": (5.0, 3000.0),
    "interconnect_gbps": (1.0, 10000.0),
}


class ValidationError(Exception):
    """The dataset does not satisfy the schema or its sanity bounds."""


def _iso(value: str, where: str) -> None:
    try:
        dt.date.fromisoformat(value)
    except (TypeError, ValueError) as exc:
        raise ValidationError(f"{where}: captured_at {value!r} is not an ISO date") from exc


def validate(data: dict) -> list[str]:
    """Raise on anything unshippable; return non-fatal notes."""
    if data.get("schema_version") != SCHEMA_VERSION:
        raise ValidationError(f"unsupported schema_version: {data.get('schema_version')!r}")
    _iso(data.get("captured_at", ""), "top level")
    gpus = data.get("gpus")
    if not isinstance(gpus, list) or not gpus:
        raise ValidationError("no gpus in dataset")

    notes: list[str] = []
    seen: set[str] = set()
    for entry in gpus:
        name = entry.get("name", "<unnamed>")
        for key in REQUIRED:
            if key not in entry:
                raise ValidationError(f"{name}: missing {key!r}")
        if name in seen:
            raise ValidationError(f"duplicate GPU name {name!r}")
        seen.add(name)
        if not str(entry["source_url"]).startswith("https://"):
            raise ValidationError(f"{name}: source_url must be https")
        _iso(entry["captured_at"], name)
        if entry["price_basis"] not in PRICE_BASES:
            raise ValidationError(
                f"{name}: price_basis {entry['price_basis']!r} not one of {sorted(PRICE_BASES)}"
            )
        if entry["tflops_basis"] not in TFLOPS_BASES:
            raise ValidationError(
                f"{name}: tflops_basis {entry['tflops_basis']!r} not one of {sorted(TFLOPS_BASES)}"
            )
        for field, (lo, hi) in BOUNDS.items():
            value = entry[field]
            if value is None:
                # A null is legal and means "no vendor source". It disables the
                # prediction that depends on it rather than defaulting.
                notes.append(f"{name}: {field} is null -- dependent predictions are unknown")
                continue
            if not isinstance(value, (int, float)):
                raise ValidationError(f"{name}: {field} is not a number")
            if not lo <= value <= hi:
                raise ValidationError(f"{name}: {field}={value} outside [{lo}, {hi}]")
        if entry["product_line"] not in PRODUCT_LINES.get(entry["vendor"], set()):
            raise ValidationError(
                f"{name}: vendor/product_line {entry['vendor']}/{entry['product_line']} "
                "not in the vocabulary"
            )
        if entry["unified_memory"] != (entry["product_line"] in UNIFIED_LINES):
            raise ValidationError(f"{name}: unified_memory disagrees with its product line")
        options = entry["memory_options_gb"]
        if entry["unified_memory"]:
            # vram_gb is the largest configuration; every configuration is listed.
            if not options or max(options) != entry["vram_gb"]:
                raise ValidationError(f"{name}: memory_options_gb must list sizes up to vram_gb")
        elif options is not None:
            raise ValidationError(f"{name}: memory_options_gb is for unified-memory devices")
        if not isinstance(entry["fp8_supported"], bool):
            raise ValidationError(f"{name}: fp8_supported must be a bool")
        # A null TFLOPS figure must say why, and a reason-for-null must not sit
        # beside a number -- otherwise an unlabeled headline could ship as dense.
        if (entry["fp16_tflops"] is None) != (entry["tflops_basis"] in TFLOPS_NULL_BASES):
            raise ValidationError(
                f"{name}: fp16_tflops={entry['fp16_tflops']!r} does not agree with "
                f"tflops_basis={entry['tflops_basis']!r}"
            )
        for field, url in (entry.get("field_sources") or {}).items():
            if field not in REQUIRED:
                raise ValidationError(f"{name}: field_sources names unknown field {field!r}")
            if not str(url).startswith("https://"):
                raise ValidationError(f"{name}: field_sources[{field}] must be https")
    return notes


def _with_identity(entry: dict) -> dict:
    vendor, line = vendor_line(entry["name"])
    return {
        **entry,
        "vendor": vendor,
        "product_line": line,
        "unified_memory": line in UNIFIED_LINES,
        "memory_options_gb": entry.get("memory_options_gb"),
    }


def build() -> dict:
    return {
        "schema_version": SCHEMA_VERSION,
        "captured_at": max(g["captured_at"] for g in GPUS),
        "note": (
            "GPU specifications with per-entry source and capture date. Values are "
            "vendor-published figures; `tflops_basis` records which column each "
            "TFLOPS number came from, since a with-sparsity headline halved is not "
            "a datasheet row. `price_basis` distinguishes an amortised purchase "
            "price from a rental rate -- the two are not the same quantity, and "
            "the field drives the budget gate and the self-host-vs-API break-even. "
            "A null field means no vendor source; it disables the prediction that "
            "depends on it rather than defaulting. Regenerate with "
            "scripts/build_hardware_data.py."
        ),
        "gpus": [_with_identity(g) for g in GPUS],
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="validate the bundled dataset")
    ap.add_argument("--write", action="store_true", help="regenerate the bundled dataset")
    args = ap.parse_args()

    if args.write:
        data = build()
        validate(data)
        DATASET.parent.mkdir(parents=True, exist_ok=True)
        DATASET.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
        print(f"wrote {DATASET} ({len(data['gpus'])} GPUs)")
        return 0

    if not DATASET.exists():
        print(f"dataset missing: {DATASET}", file=sys.stderr)
        return 1
    data = json.loads(DATASET.read_text(encoding="utf-8"))
    notes = validate(data)
    for note in notes:
        print(f"  note: {note}")
    print(f"OK: {len(data['gpus'])} GPUs, captured {data['captured_at']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
