"""Self-host vs hosted-API cost comparison and break-even volume.

Answers the question that comes *before* "which GPU": is self-hosting worth it at
all, at this volume? Self-hosting is a fixed monthly bill for a fixed capacity; an
API is a per-token charge that scales with use. They cross at one volume, and the
whole decision turns on which side of it you are on.

Two honesty constraints shape this module:

- **Prices are a dated snapshot, not a live feed.** No vendor publishes a pricing
  API, so ``data/api_pricing.json`` is regenerated by ``scripts/build_cost_data.py``
  and carries ``captured_at`` plus a source URL per provider. Past
  ``STALE_AFTER_DAYS`` it is reported as stale rather than quoted as current.
- **An 8B you host is not a frontier API.** Each entry carries a ``class``:
  ``open`` (the same class of open-weights model, hosted for you) is the
  like-for-like cost comparison; ``frontier`` is a different quality tier and is
  labeled so the number cannot be read as apples-to-apples.
"""

from __future__ import annotations

import datetime as _dt
import json
from dataclasses import dataclass, field
from functools import lru_cache
from importlib import resources

from chimeraforge.planner.constants import SECONDS_PER_MONTH

# Re-exported from constants so a month means the same thing here and in the
# cost model; imported by name in tests and callers.
TOKENS_PER_MILLION = 1_000_000
# Published list prices drift. Past this the snapshot is reported as stale rather
# than presented as current: long enough not to cry wolf on a fresh release, short
# enough that a real price change does not go unflagged for long.
STALE_AFTER_DAYS = 90


class PricingError(RuntimeError):
    """Raised when the bundled pricing snapshot is missing or unusable."""


@dataclass(frozen=True)
class ApiOption:
    """One hosted model priced against the planned workload."""

    key: str
    provider: str
    name: str
    model_class: str
    input_per_1m: float
    output_per_1m: float
    monthly_cost: float
    cost_per_request: float
    # Monthly output-token volume at which self-hosting and the API cost the same.
    breakeven_tokens_month: float | None
    # True when self-hosting is cheaper at the planned volume.
    self_host_cheaper: bool

    def to_dict(self) -> dict:
        return {
            "key": self.key,
            "provider": self.provider,
            "name": self.name,
            "class": self.model_class,
            "input_per_1m_usd": self.input_per_1m,
            "output_per_1m_usd": self.output_per_1m,
            "monthly_cost_usd": round(self.monthly_cost, 2),
            "cost_per_request_usd": round(self.cost_per_request, 6),
            "breakeven_output_tokens_month": (
                round(self.breakeven_tokens_month)
                if self.breakeven_tokens_month is not None
                else None
            ),
            "self_host_cheaper": self.self_host_cheaper,
        }


@dataclass
class ApiComparison:
    """Self-host monthly cost set against every priced hosted option."""

    self_host_monthly: float
    requests_per_month: float
    prompt_tokens: int
    output_tokens: int
    captured_at: str
    age_days: int
    stale: bool
    options: list[ApiOption] = field(default_factory=list)
    sources: dict[str, str] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "self_host_monthly_usd": round(self.self_host_monthly, 2),
            "requests_per_month": round(self.requests_per_month),
            "prompt_tokens": self.prompt_tokens,
            "output_tokens": self.output_tokens,
            "prices_captured_at": self.captured_at,
            "prices_age_days": self.age_days,
            "prices_stale": self.stale,
            "sources": dict(self.sources),
            "options": [o.to_dict() for o in self.options],
        }


@lru_cache(maxsize=1)
def load_pricing() -> dict:
    """Load the bundled price snapshot (packaged via importlib.resources)."""
    try:
        text = (
            resources.files("chimeraforge.planner.data")
            .joinpath("api_pricing.json")
            .read_text(encoding="utf-8")
        )
    except (FileNotFoundError, ModuleNotFoundError) as exc:  # pragma: no cover
        raise PricingError("bundled api_pricing.json is missing") from exc
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        raise PricingError(f"bundled api_pricing.json is not valid JSON: {exc}") from exc


def snapshot_age_days(captured_at: str, today: _dt.date | None = None) -> int:
    """Whole days between the snapshot date and ``today`` (never negative)."""
    try:
        captured = _dt.date.fromisoformat(captured_at)
    except ValueError as exc:
        raise PricingError(f"captured_at {captured_at!r} is not an ISO date") from exc
    return max(((today or _dt.date.today()) - captured).days, 0)


def api_monthly_cost(
    *,
    requests_per_month: float,
    prompt_tokens: int,
    output_tokens: int,
    input_per_1m: float,
    output_per_1m: float,
) -> float:
    """Monthly API spend for a workload, charging input and output separately."""
    per_request = (
        prompt_tokens * input_per_1m + output_tokens * output_per_1m
    ) / TOKENS_PER_MILLION
    return per_request * requests_per_month


def breakeven_output_tokens(
    *,
    self_host_monthly: float,
    prompt_tokens: int,
    output_tokens: int,
    input_per_1m: float,
    output_per_1m: float,
) -> float | None:
    """Monthly *output* tokens at which API spend equals the self-host bill.

    Expressed in output tokens because that is the unit the planner already
    reports throughput in; the prompt is charged alongside at the workload's own
    prompt:output ratio. ``None`` when the API costs nothing (no crossing point).
    """
    if output_tokens <= 0:
        return None
    cost_per_request = (
        prompt_tokens * input_per_1m + output_tokens * output_per_1m
    ) / TOKENS_PER_MILLION
    if cost_per_request <= 0:
        return None
    return (self_host_monthly / cost_per_request) * output_tokens


def compare(
    *,
    self_host_monthly: float,
    request_rate: float,
    prompt_tokens: int,
    output_tokens: int,
    pricing: dict | None = None,
    today: _dt.date | None = None,
) -> ApiComparison:
    """Price the planned workload against every hosted option in the snapshot."""
    data = pricing if pricing is not None else load_pricing()
    captured_at = data.get("captured_at", "")
    # No date at all is treated as maximally stale rather than silently trusted.
    age = snapshot_age_days(captured_at, today) if captured_at else STALE_AFTER_DAYS + 1
    requests_per_month = max(request_rate, 0.0) * SECONDS_PER_MONTH

    options: list[ApiOption] = []
    sources: dict[str, str] = {}
    for provider, block in data.get("providers", {}).items():
        sources[provider] = block.get("source_url", "")
        for key, m in block.get("models", {}).items():
            monthly = api_monthly_cost(
                requests_per_month=requests_per_month,
                prompt_tokens=prompt_tokens,
                output_tokens=output_tokens,
                input_per_1m=m["input_per_1m"],
                output_per_1m=m["output_per_1m"],
            )
            options.append(
                ApiOption(
                    key=f"{provider}:{key}",
                    provider=provider,
                    name=m["name"],
                    model_class=block.get("class", "unknown"),
                    input_per_1m=m["input_per_1m"],
                    output_per_1m=m["output_per_1m"],
                    monthly_cost=monthly,
                    cost_per_request=(monthly / requests_per_month if requests_per_month else 0.0),
                    breakeven_tokens_month=breakeven_output_tokens(
                        self_host_monthly=self_host_monthly,
                        prompt_tokens=prompt_tokens,
                        output_tokens=output_tokens,
                        input_per_1m=m["input_per_1m"],
                        output_per_1m=m["output_per_1m"],
                    ),
                    self_host_cheaper=self_host_monthly < monthly,
                )
            )
    options.sort(key=lambda o: o.monthly_cost)
    return ApiComparison(
        self_host_monthly=self_host_monthly,
        requests_per_month=requests_per_month,
        prompt_tokens=prompt_tokens,
        output_tokens=output_tokens,
        captured_at=captured_at,
        age_days=age,
        stale=age > STALE_AFTER_DAYS,
        options=options,
        sources=sources,
    )
