"""Grid carbon intensity for operational emissions per token.

Emissions are the planner's energy figure times the carbon intensity of the grid
(SCI v1.1: ``O = E x I``). Intensity is a property of the region, so it comes from
a bundled snapshot of Our World in Data's ``carbon_intensity_elec`` -- Ember's
annual-average lifecycle gCO2e/kWh -- pinned to an OWID commit and regenerated by
``scripts/build_carbon_data.py``. A user figure (e.g. a marginal or hourly value
from their provider) replaces it with ``--carbon-intensity``.
"""

from __future__ import annotations

import datetime as _dt
import json
from dataclasses import dataclass
from functools import lru_cache
from importlib import resources

# A region's figure older than this many calendar years is reported as stale:
# grids decarbonise fast enough that a few years moves the number materially.
CARBON_STALE_AFTER_YEARS = 2
# Upper bound for a user-supplied figure; the dirtiest grids sit near 1000-1300.
MAX_CARBON_INTENSITY = 2000.0
SOURCE_CUSTOM = "custom"


class CarbonError(ValueError):
    """A grid region or intensity figure cannot be used."""


@dataclass(frozen=True)
class GridIntensity:
    """The carbon intensity a plan's emissions are computed against."""

    region: str
    name: str
    gco2e_per_kwh: float
    year: int | None
    basis: str
    stale: bool


@lru_cache(maxsize=1)
def load_carbon() -> dict:
    """Load the bundled carbon-intensity snapshot (packaged via importlib.resources)."""
    try:
        text = (
            resources.files("chimeraforge.planner.data")
            .joinpath("carbon_intensity.json")
            .read_text(encoding="utf-8")
        )
    except (FileNotFoundError, ModuleNotFoundError) as exc:  # pragma: no cover
        raise CarbonError("bundled carbon_intensity.json is missing") from exc
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:  # pragma: no cover
        raise CarbonError(f"bundled carbon_intensity.json is not valid JSON: {exc}") from exc


def _find_region(query: str, data: dict) -> str:
    key = query.strip().upper()
    if key in data["regions"] or key in data.get("excluded", {}):
        return key
    by_name = [iso for iso, r in data["regions"].items() if r["name"].upper() == key]
    if by_name:
        return by_name[0]
    near = sorted(
        f"{iso} ({r['name']})"
        for iso, r in data["regions"].items()
        if key and key in r["name"].upper()
    )[:5]
    hint = f" Did you mean: {', '.join(near)}?" if near else ""
    raise CarbonError(
        f"unknown grid region {query!r}: use an ISO-3166 alpha-3 code (USA, DEU, FRA) "
        f"or a country name.{hint}"
    )


def grid_intensity(
    region: str | None,
    custom_gco2e_per_kwh: float | None = None,
    today: _dt.date | None = None,
) -> GridIntensity | None:
    """Resolve ``--grid-region`` / ``--carbon-intensity`` to one figure, or None when off.

    Raises:
        CarbonError: both given, an unknown or excluded region, or a figure out of range.
    """
    if region is None and custom_gco2e_per_kwh is None:
        return None
    if region is not None and custom_gco2e_per_kwh is not None:
        raise CarbonError("pass a grid region or a carbon_intensity figure, not both")
    if custom_gco2e_per_kwh is not None:
        if not 0 < custom_gco2e_per_kwh <= MAX_CARBON_INTENSITY:
            raise CarbonError(
                f"carbon_intensity must be in (0, {MAX_CARBON_INTENSITY:.0f}] gCO2e/kWh"
            )
        return GridIntensity(
            region=SOURCE_CUSTOM,
            name=SOURCE_CUSTOM,
            gco2e_per_kwh=float(custom_gco2e_per_kwh),
            year=None,
            basis=f"your figure ({custom_gco2e_per_kwh:g} gCO2e/kWh)",
            stale=False,
        )
    data = load_carbon()
    iso = _find_region(region, data)
    if iso in data.get("excluded", {}):
        raise CarbonError(
            f"grid region {iso} is excluded from the snapshot: {data['excluded'][iso]}"
        )
    r = data["regions"][iso]
    src = data["source"]
    year = int(r["year"])
    stale = (today or _dt.date.today()).year - year > CARBON_STALE_AFTER_YEARS
    return GridIntensity(
        region=iso,
        name=r["name"],
        gco2e_per_kwh=float(r["gco2e_per_kwh"]),
        year=year,
        basis=(
            f"{r['name']} {year} annual-average lifecycle grid intensity, "
            f"{r['gco2e_per_kwh']:g} gCO2e/kWh (Ember via Our World in Data, "
            f"{src['license'].split(' (')[0]}; OWID {src['commit'][:7]})"
        ),
        stale=stale,
    )
