"""GPU hardware specifications database.

Provides VRAM, memory bandwidth, and approximate hourly cost for
consumer and data-center GPUs. Bandwidth ratios relative to the
reference GPU (RTX 4080) are used to extrapolate throughput for
untested hardware.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
from dataclasses import dataclass, replace
from importlib.resources import files

# How a `$/hr` figure was arrived at. These are not the same quantity: an
# amortised purchase price and a rental rate answer different questions, and the
# field drives the budget gate, $/1M-tok and the self-host-vs-API break-even. It
# used to be one field mixing both, with its own comment admitting as much.
PRICE_BASIS_MARKETPLACE = "marketplace"
PRICE_BASIS_HYPERSCALER = "hyperscaler-on-demand"
PRICE_BASIS_AMORTISED = "amortised-purchase"

# Prose for each, so a plan can state which basis it priced against instead of
# printing a bare dollar figure that means two different things.
PRICE_BASIS_PHRASE = {
    PRICE_BASIS_MARKETPLACE: (
        "GPU marketplace rate -- roughly 4-5x below hyperscaler on-demand for the same part"
    ),
    PRICE_BASIS_HYPERSCALER: "hyperscaler on-demand list rate",
    PRICE_BASIS_AMORTISED: (
        "amortised card purchase price, not a rental rate -- it excludes power, "
        "which is reported separately, and every other running cost"
    ),
}


@dataclass(frozen=True)
class GPUSpec:
    name: str
    vram_gb: float
    bandwidth_gbps: float  # Memory bandwidth in GB/s (decode/TPOT is bound by this)
    cost_per_hour: float  # $/hr -- see `price_basis` for WHICH quantity
    fp16_tflops: float = 0.0  # Dense FP16 Tensor TFLOPS, FP32 accumulate (prefill/TTFT)
    tdp_watts: float = 0.0  # Board TDP in watts (energy cost + perf/watt; 0 = unknown)
    # Per-GPU interconnect bandwidth in GB/s (bidirectional aggregate) for tensor-
    # parallel all-reduce: NVLink on datacenter SXM, PCIe on consumer. 0 = unknown.
    interconnect_gbps: float = 0.0
    # Native FP8 tensor cores (0.15.0). Serving an FP8 checkpoint on a GPU without
    # them means emulation or an outright refusal from the backend, so the planner
    # will not offer FP8 there. Ada / Hopper / Blackwell / CDNA3 have it; Ampere
    # (RTX 30, A100) and Turing (T4) do not.
    fp8_supported: bool = True
    # Which quantity `cost_per_hour` is (P8.6). Defaults to the consumer basis so
    # a hand-built GPUSpec cannot silently claim to be a cloud rate.
    price_basis: str = PRICE_BASIS_AMORTISED
    # Which datasheet column `fp16_tflops` came from. A with-sparsity headline
    # halved is defensible but is not a datasheet row, and the halving heuristic
    # is not universally safe -- AMD publishes no sparsity figure at all for some
    # parts, so halving their headline would understate a dense number by 2x.
    tflops_basis: str = "dense"
    # Where the figures came from, and when they were read.
    source_url: str = ""
    captured_at: str = ""
    # A user-supplied spec, not a bundled one. Its numbers are the user's claim,
    # not a vendor-published figure this project checked.
    user_supplied: bool = False


# Reference GPU - all TR measurements collected on this card
REFERENCE_GPU = "RTX 4080 12GB"

# Provenance lives in the dataset, per entry: `source_url`, `captured_at`,
# `tflops_basis` (which datasheet column the TFLOPS figure came from) and
# `price_basis` (whether $/hr is a rental rate or an amortised purchase).
# Regenerate with scripts/build_hardware_data.py, which validates it.


def _load_bundled() -> dict[str, GPUSpec]:
    """Load the dataset, which is regenerated by scripts/build_hardware_data.py.

    The table used to be 22 hand-typed literals with a prose comment for
    provenance -- no capture date, no per-entry source, no regeneration path --
    in the one dataset that drives every throughput number, since decode is
    modelled as bandwidth-bound.
    """
    raw = json.loads(
        files("chimeraforge.planner.data").joinpath("hardware.json").read_text(encoding="utf-8")
    )
    out: dict[str, GPUSpec] = {}
    for entry in raw["gpus"]:
        out[entry["name"]] = GPUSpec(
            name=entry["name"],
            vram_gb=entry["vram_gb"],
            bandwidth_gbps=entry["bandwidth_gbps"],
            cost_per_hour=entry["cost_per_hour"],
            fp16_tflops=entry["fp16_tflops"] or 0.0,
            tdp_watts=entry["tdp_watts"] or 0.0,
            interconnect_gbps=entry["interconnect_gbps"] or 0.0,
            fp8_supported=entry["fp8_supported"],
            price_basis=entry["price_basis"],
            tflops_basis=entry["tflops_basis"],
            source_url=entry["source_url"],
            captured_at=entry["captured_at"],
        )
    return out


GPU_DB: dict[str, GPUSpec] = _load_bundled()


def get_gpu(name: str) -> GPUSpec | None:
    """Look up GPU by name (case-insensitive partial match).

    A blank name matches nothing. It used to fall through to the substring loop,
    where `"" in key.lower()` is true for every entry, so `--hardware "$GPU"`
    with GPU unset returned the first row in GPU_DB and the planner produced a
    fully provenance-labelled plan for a card the user never named.
    """
    if not name or not name.strip():
        return None
    name_lower = name.strip().lower()
    for key, spec in GPU_DB.items():
        if key.lower() == name_lower:
            return spec
    for key, spec in GPU_DB.items():
        if name_lower in key.lower() or key.lower() in name_lower:
            return spec
    return None


def is_reference_hardware(target_gpu: str | None) -> bool:
    """True when this GPU is the rig the bundled corpus was actually measured on.

    Every row in the corpus came off ``REFERENCE_GPU``; the lookup key is
    ``model|backend|quant`` and carries no hardware. So a lookup hit is only
    evidence about THIS GPU when this GPU is that one -- on anything else the
    number has been through ``bandwidth_ratio`` and is an extrapolation.

    ``None`` counts as reference: callers that pass no hardware get the unscaled
    measurement itself.
    """
    if target_gpu is None:
        return True
    target = get_gpu(target_gpu)
    ref = GPU_DB.get(REFERENCE_GPU)
    if target is None or ref is None:
        return False
    return target.name == ref.name


def bandwidth_ratio(target_gpu: str) -> float:
    """Throughput scaling ratio: target bandwidth / reference bandwidth.

    Used to extrapolate throughput from RTX 4080 measurements to other GPUs.
    Returns 1.0 for the reference GPU or unknown GPUs.
    """
    ref = GPU_DB.get(REFERENCE_GPU)
    target = get_gpu(target_gpu)
    if ref is None or target is None:
        return 1.0
    return target.bandwidth_gbps / ref.bandwidth_gbps


# Fields a caller may supply for a GPU the dataset does not carry, mapped to the
# CLI flag that sets each. The planner is model-agnostic by design and was
# hardware-locked by accident: an unlisted model can be planned with --params-b,
# and an unlisted GPU could not be planned at all.
GPU_OVERRIDE_FIELDS = {
    "vram_gb": "--gpu-vram-gb",
    "bandwidth_gbps": "--gpu-bandwidth-gbps",
    "fp16_tflops": "--gpu-fp16-tflops",
    "tdp_watts": "--gpu-tdp-w",
    "interconnect_gbps": "--gpu-interconnect-gbps",
    "cost_per_hour": "--gpu-price-per-hour",
}
# Without these two nothing can be sized or priced, so they are the minimum for
# an unlisted card. Everything else degrades one specific prediction rather than
# blocking the plan.
GPU_OVERRIDE_REQUIRED = ("vram_gb", "bandwidth_gbps")

AUTO_HARDWARE = "auto"


class HardwareError(ValueError):
    """The requested hardware cannot be resolved as specified."""


def spec_from_overrides(name: str, overrides: dict) -> GPUSpec:
    """Build a GPUSpec from user-supplied figures.

    The result is marked ``user_supplied`` and carries no source URL, because
    these are the caller's numbers and this project has not checked them against
    a vendor page. A field left out stays 0.0, which reads as "unknown" to every
    consumer -- it disables the prediction that depends on it rather than
    silently inheriting the reference card's value.
    """
    supplied = {k: v for k, v in overrides.items() if k in GPU_OVERRIDE_FIELDS and v is not None}
    missing = [GPU_OVERRIDE_FIELDS[k] for k in GPU_OVERRIDE_REQUIRED if not supplied.get(k)]
    if missing:
        optional = ", ".join(
            flag for key, flag in GPU_OVERRIDE_FIELDS.items() if key not in GPU_OVERRIDE_REQUIRED
        )
        raise HardwareError(
            f"{name!r} is not in the GPU database, and sizing it needs at least "
            f"{' and '.join(missing)}. Pass those (plus any of {optional}) to plan "
            f"an unlisted card."
        )
    return GPUSpec(
        name=name,
        vram_gb=float(supplied["vram_gb"]),
        bandwidth_gbps=float(supplied["bandwidth_gbps"]),
        cost_per_hour=float(supplied.get("cost_per_hour", 0.0)),
        fp16_tflops=float(supplied.get("fp16_tflops", 0.0)),
        tdp_watts=float(supplied.get("tdp_watts", 0.0)),
        interconnect_gbps=float(supplied.get("interconnect_gbps", 0.0)),
        # An unlisted card's FP8 support is not knowable from the figures given,
        # and offering FP8 on a part that emulates it hands out a config that
        # does not run. Refused rather than assumed.
        fp8_supported=False,
        price_basis=PRICE_BASIS_AMORTISED,
        tflops_basis="unlabeled-by-vendor",
        user_supplied=True,
    )


# Trailing capacity token in a database key ("RTX 4090 24GB" -> "RTX 4090"), so a
# driver name can be matched on the model alone and disambiguated by the VRAM the
# driver actually reported.
_CAPACITY_TOKEN = re.compile(r"\s*\d+(?:\.\d+)?\s*GB\s*$", re.I)
# Vendor and brand words a driver prepends. Dropped so "NVIDIA GeForce RTX 4090"
# and "NVIDIA A100-SXM4-80GB" both reduce to something the keys can be found in.
_DRIVER_NOISE = re.compile(r"\b(nvidia|geforce|tesla|quadro|advanced micro devices|amd)\b", re.I)


def match_driver_name(driver_name: str, vram_gb: float | None = None) -> GPUSpec | None:
    """Match a driver-reported GPU name to a database entry, or None.

    `get_gpu` is a substring match in either direction, which cannot connect
    ``"NVIDIA GeForce RTX 4090"`` to the key ``"RTX 4090 24GB"`` -- neither
    contains the other. So `--hardware auto` would have failed to recognise the
    most common consumer card in the database.

    Matching is on the model portion of the key, longest first, so ``RTX 4060``
    cannot claim a driver that said ``RTX 4060 Ti``. Where several capacities of
    one model exist, the driver's reported VRAM picks between them; without a
    VRAM figure an ambiguous model is **not** matched, because guessing 8 GB for
    a 16 GB card silently halves every VRAM verdict.
    """
    if not driver_name or not driver_name.strip():
        return None
    haystack = _DRIVER_NOISE.sub(" ", driver_name).lower()
    haystack = re.sub(r"[-_]+", " ", haystack)
    haystack = re.sub(r"\s+", " ", haystack).strip()

    matches: list[tuple[int, GPUSpec]] = []
    for key, spec in GPU_DB.items():
        model = _CAPACITY_TOKEN.sub("", key).strip().lower()
        if model and model in haystack:
            matches.append((len(model), spec))
    if not matches:
        return None

    longest = max(n for n, _ in matches)
    best = [spec for n, spec in matches if n == longest]
    if len(best) == 1:
        return best[0]
    if vram_gb is None:
        return None
    return min(best, key=lambda s: abs(s.vram_gb - vram_gb))


def detect_local_gpu() -> tuple[str, float] | None:
    """The installed GPU's driver-reported name and VRAM, or None.

    Tries pynvml, then ``nvidia-smi``. Reports only what the driver actually
    says: the name and the memory. Bandwidth and TFLOPS are NOT inferred from
    the name, because a name match that is wrong is worse than no match -- it
    produces a fully provenance-labelled plan for a card the user does not have.
    """
    try:  # pragma: no cover - depends on a local driver
        import pynvml

        pynvml.nvmlInit()
        try:
            handle = pynvml.nvmlDeviceGetHandleByIndex(0)
            raw = pynvml.nvmlDeviceGetName(handle)
            name = raw.decode() if isinstance(raw, bytes) else str(raw)
            vram = pynvml.nvmlDeviceGetMemoryInfo(handle).total / (1024**3)
            return name, round(vram, 1)
        finally:
            pynvml.nvmlShutdown()
    except Exception:  # noqa: BLE001 - no driver is not an error here
        pass

    exe = shutil.which("nvidia-smi")
    if not exe:
        return None
    try:  # pragma: no cover - depends on a local driver
        out = subprocess.run(
            [exe, "--query-gpu=name,memory.total", "--format=csv,noheader,nounits"],
            capture_output=True,
            text=True,
            timeout=10,
            check=True,
        ).stdout.strip()
    except Exception:  # noqa: BLE001 - reported by the caller as "not detected"
        return None
    if not out:
        return None
    name, _, mib = out.splitlines()[0].partition(",")
    try:
        vram = float(mib.strip()) / 1024.0
    except ValueError:
        return None
    return name.strip(), round(vram, 1)


def resolve_hardware(name: str, overrides: dict | None = None) -> tuple[GPUSpec, list[str]]:
    """Resolve a hardware name to a spec, with the warnings resolution earned.

    Priority: ``auto`` detection, then the bundled dataset, then user-supplied
    figures for a card the dataset does not carry. ``auto`` that matches a known
    part uses the dataset's full figures; ``auto`` that does not falls back to
    the driver's name and VRAM with bandwidth left UNKNOWN, rather than
    borrowing another card's numbers.
    """
    overrides = overrides or {}
    warnings: list[str] = []
    supplied = {k: v for k, v in overrides.items() if k in GPU_OVERRIDE_FIELDS and v is not None}

    if name and name.strip().lower() == AUTO_HARDWARE:
        detected = detect_local_gpu()
        if detected is None:
            raise HardwareError(
                "--hardware auto found no NVIDIA GPU (pynvml is absent or failed, "
                "and nvidia-smi is absent or returned nothing). Name the card "
                f"explicitly, or supply {GPU_OVERRIDE_FIELDS['vram_gb']} and "
                f"{GPU_OVERRIDE_FIELDS['bandwidth_gbps']}."
            )
        driver_name, driver_vram = detected
        known = match_driver_name(driver_name, driver_vram)
        if known is not None:
            warnings.append(
                f"--hardware auto detected {driver_name!r}, matched to "
                f"{known.name!r} in the database"
            )
            return known, warnings
        merged = {"vram_gb": driver_vram, **supplied}
        if not merged.get("bandwidth_gbps"):
            raise HardwareError(
                f"detected {driver_name!r} ({driver_vram} GB), which is not in the "
                "GPU database, and its memory bandwidth is not knowable from the "
                f"driver. Pass {GPU_OVERRIDE_FIELDS['bandwidth_gbps']} to plan it -- "
                "decode is bandwidth-bound, so without it throughput is unknown."
            )
        warnings.append(
            f"--hardware auto detected {driver_name!r} ({driver_vram} GB), which is "
            "not in the database. VRAM is the driver's figure; the rest are yours"
        )
        return spec_from_overrides(driver_name, merged), warnings

    known = get_gpu(name)
    if known is not None:
        if supplied:
            # An override on a known card is a deliberate correction, not a
            # fallback, and it makes the entry the user's claim rather than the
            # dataset's -- so the provenance fields are cleared with it.
            spec = replace(
                known,
                user_supplied=True,
                source_url="",
                captured_at="",
                **{k: float(v) for k, v in supplied.items()},
            )
            flags = ", ".join(sorted(GPU_OVERRIDE_FIELDS[k] for k in supplied))
            warnings.append(
                f"{flags} override the bundled figures for {known.name}; those are "
                "your numbers, not vendor-sourced"
            )
            return spec, warnings
        return known, warnings

    spec = spec_from_overrides(name, supplied)
    warnings.append(
        f"{name!r} is not in the GPU database; its specs are yours, not "
        "vendor-published, so every prediction downstream rests on them"
    )
    return spec, warnings
